
name: Set status

on:
  workflow_call:
    inputs:
      state:
        description: The state of the status. Can be one of 'error', 'failure', 'pending', 'success'
        required: true
        type: string
      context:
        description: The name of the status, as it will be presented on the commit status
        required: true
        type: string
      description:
        description: The description of the status, as it will be presented on the commit status
        required: true
        type: string
      url:
        description: The URL to open in the 'details' link on the commit status.
        default: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        required: false
        type: string

permissions:
  statuses: write      

jobs:
  status:
    runs-on: ubuntu-latest
    steps:
    
    - name: Set status
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{ github.repository }}/statuses/${{ github.sha }} \
          -f "state=${{ inputs.state }}" \
          -f "target_url=${{ inputs.url }}" \
          -f "description=${{ inputs.description }}" \
          -f "context=${{ inputs.context }}"

