
name: Set status

on:
  workflow_call:
    inputs:
      state:
        required: true
        type: string
      description:
        required: true
        type: string
      context:
        required: true
        type: string

permissions:
  statuses: write      

jobs:
  status:
    runs-on: ubuntu-latest
    steps:
    
    - name: Set status
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{ github.repository }}/statuses/${{ github.sha }} \
          -f "state=${{ inputs.state }}" \
          -f "target_url=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
          -f "description=${{ inputs.description }}" \
          -f "context=${{ inputs.context }}"

